# Generated by Django 4.0.2 on 2022-02-21 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orm.role'),
        ),
    ]
