# Generated by Django 4.0.2 on 2022-02-21 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_alter_student_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='orm.role'),
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
