# Generated by Django 4.0.2 on 2022-02-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0006_remove_employe_department_ptr_delete_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='role_id',
        ),
    ]
