# Generated by Django 4.0.2 on 2022-02-21 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0007_remove_student_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='orm.role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_phone',
            field=models.CharField(max_length=50),
        ),
    ]
