# Generated by Django 4.0.2 on 2022-02-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0008_student_role_id_alter_employee_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_phone',
            field=models.CharField(max_length=50),
        ),
    ]
