# Generated by Django 4.0.2 on 2022-02-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='employe_contact',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employe',
            name='employe_name',
            field=models.CharField(max_length=20),
        ),
    ]
